[2023-12-20 16:31:27,692: INFO: main: Welcome to our custom log]
[2023-12-27 12:11:21,118: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-27 12:11:21,121: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-27 12:11:21,123: INFO: common: created directory at: artifacts]
[2023-12-27 12:23:54,542: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-27 12:23:54,544: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-27 12:23:54,545: INFO: common: created directory at: artifacts]
[2023-12-27 12:23:54,547: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-27 12:23:54,548: INFO: 3525658959: Downloading data from https://drive.google.com/file/d/1oq-vYP-OzV85Nc4v6c-R5tYblyuGGJqy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-27 12:25:48,691: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-27 12:25:48,693: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-27 12:25:48,695: INFO: common: created directory at: artifacts]
[2023-12-27 12:25:48,696: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-27 12:25:48,697: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1oq-vYP-OzV85Nc4v6c-R5tYblyuGGJqy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-27 12:28:38,077: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1oq-vYP-OzV85Nc4v6c-R5tYblyuGGJqy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-28 14:46:12,615: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-02-28 14:46:12,617: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-28 14:46:12,618: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-28 14:46:12,618: INFO: common: created directory at: artifacts]
[2024-02-28 14:46:12,618: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-28 14:46:12,619: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1oq-vYP-OzV85Nc4v6c-R5tYblyuGGJqy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-28 14:46:14,745: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1oq-vYP-OzV85Nc4v6c-R5tYblyuGGJqy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-28 14:46:14,746: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    obj.main()
  File "d:\kidney-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.extract_zip_file()
  File "d:\kidney-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 43, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\vaish\anaconda3\envs\kidney\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-02-28 14:52:58,888: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-02-28 14:52:58,889: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-28 14:52:58,890: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-28 14:52:58,890: INFO: common: created directory at: artifacts]
[2024-02-28 14:52:58,890: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-28 14:52:58,890: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1oq-vYP-OzV85Nc4v6c-R5tYblyuGGJqy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-28 14:53:01,014: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1oq-vYP-OzV85Nc4v6c-R5tYblyuGGJqy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-28 14:53:01,014: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    obj.main()
  File "d:\kidney-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.extract_zip_file()
  File "d:\kidney-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 43, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\vaish\anaconda3\envs\kidney\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-02-28 14:57:12,452: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-02-28 14:57:12,454: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-28 14:57:12,454: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-28 14:57:12,455: INFO: common: created directory at: artifacts]
[2024-02-28 14:57:12,455: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-28 14:57:12,455: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1oq-vYP-OzV85Nc4v6c-R5tYblyuGGJqy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-28 14:57:15,005: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1oq-vYP-OzV85Nc4v6c-R5tYblyuGGJqy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-28 14:57:15,401: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x=========x]
